### ISSUE TITLE
Add test cases for deployment health and metrics endpoints

### ISSUE THREAD

**Issue by ChrisRousey** [DataCater/datacater#70] opened 2022-11-24 11:14 UTC
We could not add tests to the health and metrics endpoints of deployments, because they would fail without the changes in the PR being in our current release.

Tests need to be added once a new release has been built with the changes from PR #69

**Comment by HknLof** [comment] 2023-04-03 08:20
Somewhat a duplicate of #193. Closing!

**Closed by HknLof** 2023-04-03 08:20 UTC
Labels: enhancement
